[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 177.6 s <<< FAILURE! -- in org.apache.hadoop.hdds.scm.TestWatchForCommit
[ERROR] org.apache.hadoop.hdds.scm.TestWatchForCommit.testWatchForCommitForRetryfailure(ReplicationLevel)[1] -- Time elapsed: 35.21 s <<< FAILURE!
[ERROR] org.apache.hadoop.hdds.scm.TestWatchForCommit.testWatchForCommitForRetryfailure(ReplicationLevel)[2] -- Time elapsed: 27.40 s <<< FAILURE!
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 59.27 s <<< FAILURE! -- in org.apache.hadoop.hdds.scm.TestWatchForCommit
[ERROR] org.apache.hadoop.hdds.scm.TestWatchForCommit.testWatchForCommitForRetryfailure(ReplicationLevel)[2] -- Time elapsed: 25.29 s <<< FAILURE!
[ERROR] Tests run: 15, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 49.33 s <<< FAILURE! -- in org.apache.hadoop.fs.ozone.TestLeaseRecovery
[ERROR] org.apache.hadoop.fs.ozone.TestLeaseRecovery.testGetCommittedBlockLengthTimeout(boolean)[1] -- Time elapsed: 0.100 s <<< FAILURE!
[ERROR] org.apache.hadoop.fs.ozone.TestLeaseRecovery.testGetCommittedBlockLengthTimeout(boolean)[2] -- Time elapsed: 0.130 s <<< FAILURE!
[ERROR]   Run 1: TestLeaseRecovery.testGetCommittedBlockLengthTimeout:400->closeIgnoringOMException:123 expected: <KEY_UNDER_LEASE_RECOVERY> but was: <KEY_NOT_FOUND>
[ERROR]   Run 1: TestLeaseRecovery.testGetCommittedBlockLengthTimeout:390 expected: <3> but was: <0>
[ERROR]   Run 1: TestWatchForCommit.testWatchForCommitForRetryfailure:295 
[ERROR]   Run 1: TestWatchForCommit.testWatchForCommitForRetryfailure:284 Expected java.util.concurrent.ExecutionException to be thrown, but nothing was thrown.
[ERROR]   Run 2: TestWatchForCommit.testWatchForCommitForRetryfailure:284 Expected java.util.concurrent.ExecutionException to be thrown, but nothing was thrown.
