rm: cannot remove '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/result/*': No such file or directory
Executing test in ozonesecure
Removing network ozonesecure_default
Network ozonesecure_default not found.
Creating network "ozonesecure_default" with the default driver
Pulling kdc (apache/ozone-testkrb5:20230318-1)...
20230318-1: Pulling from apache/ozone-testkrb5
Digest: sha256:6a7eeac1ebd12e8968e34ab93fb8d21f2b92ae52bc0a85b662a2d41065f05d3a
Status: Downloaded newer image for apache/ozone-testkrb5:20230318-1
Pulling kms (apache/hadoop:3)...
3: Pulling from apache/hadoop
Digest: sha256:1c33d429560ebc1b4fba1d61758ff5c73a2c9027572568769f56a68c4eaadbf6
Status: Downloaded newer image for apache/hadoop:3
Pulling datanode (apache/ozone-runner:20230104-1)...
20230104-1: Pulling from apache/ozone-runner
Digest: sha256:bc4c3ecdf9e653e2287e8b99449222807ee6011b520beae9a8874d9b8fc037f3
Status: Downloaded newer image for apache/ozone-runner:20230104-1
Creating ozonesecure_kdc_1 ... 
Creating ozonesecure_kms_1 ... 
Creating ozonesecure_httpfs_1 ... 
Creating ozonesecure_s3g_1    ... 
Creating ozonesecure_recon_1  ... 
Creating ozonesecure_datanode_1 ... 
Creating ozonesecure_datanode_2 ... 
Creating ozonesecure_datanode_3 ... 
Creating ozonesecure_om_1       ... 
Creating ozonesecure_scm_1      ... 
Creating ozonesecure_kdc_1      ... done
Creating ozonesecure_recon_1    ... done
Creating ozonesecure_s3g_1      ... done
Creating ozonesecure_httpfs_1   ... done
Creating ozonesecure_datanode_2 ... done
Creating ozonesecure_kms_1      ... done
Creating ozonesecure_om_1       ... done
Creating ozonesecure_datanode_1 ... done
Creating ozonesecure_scm_1      ... done
Creating ozonesecure_datanode_3 ... done
SECONDS: 330
com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 1 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 1. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 2 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 2. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 3 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 3. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 4 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 4. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 5 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 5. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 6 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 6. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 7 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 7. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 8 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 8. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 9 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 9. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm/172.18.0.8 to scm:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy21.submitRequest over nodeId=scmNodeId,nodeAddress=scm/172.18.0.8:9860 after 10 failover attempts. Trying to failover after sleeping for 2000ms. Current retry count: 10. SCM is in safe mode. validated:false, DataNodeSafeModeRule, registered datanodes (=0) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
WARNING! Safemode is still on. Please check the docker-compose files
Stopping ozonesecure_datanode_1 ... 
Stopping ozonesecure_scm_1      ... 
Stopping ozonesecure_datanode_2 ... 
Stopping ozonesecure_om_1       ... 
Stopping ozonesecure_datanode_3 ... 
Stopping ozonesecure_s3g_1      ... 
Stopping ozonesecure_recon_1    ... 
Stopping ozonesecure_httpfs_1   ... 
Stopping ozonesecure_kms_1      ... 
Stopping ozonesecure_kdc_1      ... 
Stopping ozonesecure_kdc_1      ... done
Stopping ozonesecure_kms_1      ... done
Stopping ozonesecure_httpfs_1   ... done
Stopping ozonesecure_recon_1    ... done
Stopping ozonesecure_om_1       ... done
Stopping ozonesecure_s3g_1      ... done
Stopping ozonesecure_datanode_1 ... done
Stopping ozonesecure_scm_1      ... done
Stopping ozonesecure_datanode_2 ... done
Stopping ozonesecure_datanode_3 ... done
Removing ozonesecure_datanode_1 ... 
Removing ozonesecure_scm_1      ... 
Removing ozonesecure_datanode_2 ... 
Removing ozonesecure_om_1       ... 
Removing ozonesecure_datanode_3 ... 
Removing ozonesecure_s3g_1      ... 
Removing ozonesecure_recon_1    ... 
Removing ozonesecure_httpfs_1   ... 
Removing ozonesecure_kms_1      ... 
Removing ozonesecure_kdc_1      ... 
Removing ozonesecure_s3g_1      ... done
Removing ozonesecure_datanode_1 ... done
Removing ozonesecure_datanode_3 ... done
Removing ozonesecure_om_1       ... done
Removing ozonesecure_httpfs_1   ... done
Removing ozonesecure_kms_1      ... done
Removing ozonesecure_datanode_2 ... done
Removing ozonesecure_kdc_1      ... done
Removing ozonesecure_recon_1    ... done
Removing ozonesecure_scm_1      ... done
Removing network ozonesecure_default
ERROR: Test execution of ozonesecure is FAILED!!!!
renamed 'ozonesecure/result/docker-ozonesecure.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/result/ozonesecure/docker-ozonesecure.log'
Exception in thread "main" java.net.SocketException: Socket closed
[ ERROR ] Reading XML source '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.4.0-SNAPSHOT/compose/result/*.xml' failed: No such file or directory

Try --help for usage information.
