-------------------------------------------------------------------------------
Test set: org.apache.hadoop.ozone.TestSecureOzoneCluster
-------------------------------------------------------------------------------
Tests run: 14, Failures: 1, Errors: 8, Skipped: 0, Time elapsed: 493.7 s <<< FAILURE! -- in org.apache.hadoop.ozone.TestSecureOzoneCluster
org.apache.hadoop.ozone.TestSecureOzoneCluster.testSecureOmReInit -- Time elapsed: 10.52 s <<< ERROR!
java.net.BindException: Problem binding to [pkrvmberfyhpb9w.internal.cloudapp.net:15013] java.net.BindException: Cannot assign requested address; For more details see:  http://wiki.apache.org/hadoop/BindException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:961)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:857)
	at org.apache.hadoop.ipc.Server.bind(Server.java:715)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:1435)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:3364)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:1195)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server.<init>(ProtobufRpcEngine2.java:485)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:452)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:375)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:986)
	at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1414)
	at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1376)
	at org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:695)
	at org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:877)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testSecureOmReInit(TestSecureOzoneCluster.java:833)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.apache.hadoop.ipc.Server.bind(Server.java:698)
	... 15 more

org.apache.hadoop.ozone.TestSecureOzoneCluster.testDelegationTokenRenewCrossSecretKeyRotation -- Time elapsed: 8.711 s <<< ERROR!
java.net.BindException: Problem binding to [pkrvmberfyhpb9w.internal.cloudapp.net:15020] java.net.BindException: Cannot assign requested address; For more details see:  http://wiki.apache.org/hadoop/BindException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:961)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:857)
	at org.apache.hadoop.ipc.Server.bind(Server.java:715)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:1435)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:3364)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:1195)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server.<init>(ProtobufRpcEngine2.java:485)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:452)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:375)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:986)
	at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1414)
	at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1376)
	at org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:695)
	at org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:877)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.setupOm(TestSecureOzoneCluster.java:716)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testDelegationTokenRenewCrossSecretKeyRotation(TestSecureOzoneCluster.java:1171)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.apache.hadoop.ipc.Server.bind(Server.java:698)
	... 16 more

org.apache.hadoop.ozone.TestSecureOzoneCluster.testCertificateRotationUnRecoverableFailure -- Time elapsed: 1.852 s <<< ERROR!
java.net.BindException: Problem binding to [pkrvmberfyhpb9w.internal.cloudapp.net:15027] java.net.BindException: Cannot assign requested address; For more details see:  http://wiki.apache.org/hadoop/BindException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:961)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:857)
	at org.apache.hadoop.ipc.Server.bind(Server.java:715)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:1435)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:3364)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:1195)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server.<init>(ProtobufRpcEngine2.java:485)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:452)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:375)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:986)
	at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1414)
	at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1376)
	at org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:695)
	at org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:877)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testCertificateRotationUnRecoverableFailure(TestSecureOzoneCluster.java:1122)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.apache.hadoop.ipc.Server.bind(Server.java:698)
	... 15 more

org.apache.hadoop.ozone.TestSecureOzoneCluster.testCertificateRotation -- Time elapsed: 3.637 s <<< ERROR!
java.net.BindException: Problem binding to [pkrvmberfyhpb9w.internal.cloudapp.net:15034] java.net.BindException: Cannot assign requested address; For more details see:  http://wiki.apache.org/hadoop/BindException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:961)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:857)
	at org.apache.hadoop.ipc.Server.bind(Server.java:715)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:1435)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:3364)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:1195)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server.<init>(ProtobufRpcEngine2.java:485)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:452)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:375)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:986)
	at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1414)
	at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1376)
	at org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:695)
	at org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:877)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testCertificateRotation(TestSecureOzoneCluster.java:968)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.apache.hadoop.ipc.Server.bind(Server.java:698)
	... 15 more

org.apache.hadoop.ozone.TestSecureOzoneCluster.testSecureOmInitSuccess -- Time elapsed: 75.70 s <<< ERROR!
org.apache.hadoop.hdds.security.x509.exception.CertificateException: Error while signing and storing SCM signed certificate.
	at org.apache.hadoop.hdds.security.x509.certificate.client.DefaultCertificateClient.signAndStoreCertificate(DefaultCertificateClient.java:1323)
	at org.apache.hadoop.hdds.security.x509.certificate.client.DefaultCertificateClient.recoverStateIfNeeded(DefaultCertificateClient.java:803)
	at org.apache.hadoop.hdds.security.x509.certificate.client.DefaultCertificateClient.initWithRecovery(DefaultCertificateClient.java:698)
	at org.apache.hadoop.ozone.om.OzoneManager.initializeSecurity(OzoneManager.java:1553)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.initializeOmStorage(TestSecureOzoneCluster.java:1371)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testSecureOmInitSuccess(TestSecureOzoneCluster.java:886)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.apache.hadoop.hdds.security.exception.SCMSecurityException: org.apache.hadoop.hdds.scm.exceptions.SCMException: org.apache.ratis.protocol.exceptions.AlreadyClosedException: SlidingWindow$Client:client-C4877CDCD2FA->RAFT is closed.
	at org.apache.hadoop.hdds.protocolPB.SCMSecurityProtocolClientSideTranslatorPB.handleError(SCMSecurityProtocolClientSideTranslatorPB.java:113)
	at org.apache.hadoop.hdds.protocolPB.SCMSecurityProtocolClientSideTranslatorPB.submitRequest(SCMSecurityProtocolClientSideTranslatorPB.java:95)
	at org.apache.hadoop.hdds.protocolPB.SCMSecurityProtocolClientSideTranslatorPB.getOMCertChain(SCMSecurityProtocolClientSideTranslatorPB.java:246)
	at org.apache.hadoop.ozone.security.OMCertificateClient.sign(OMCertificateClient.java:117)
	at org.apache.hadoop.hdds.security.x509.certificate.client.DefaultCertificateClient.signAndStoreCertificate(DefaultCertificateClient.java:1299)
	... 8 more

org.apache.hadoop.ozone.TestSecureOzoneCluster.testAccessControlExceptionOnClient -- Time elapsed: 301.9 s <<< ERROR!
java.util.concurrent.TimeoutException: testAccessControlExceptionOnClient() timed out after 5 minutes
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.io.InterruptedIOException: DestHost:destPort 10.1.0.101:15055 , LocalHost:localPort pkrvmberfyhpb9w/10.1.0.36:0. Failed on local exception: java.io.InterruptedIOException: Interrupted while waiting for IO on channel java.nio.channels.SocketChannel[connection-pending remote=10.1.0.101/10.1.0.101:15055]. Total timeout mills is 20000, 17267 millis timeout left.
		at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
		at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:961)
		at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:936)
		at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1588)
		at org.apache.hadoop.ipc.Client.call(Client.java:1529)
		at org.apache.hadoop.ipc.Client.call(Client.java:1426)
		at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:250)
		at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:132)
		at jdk.proxy2/jdk.proxy2.$Proxy118.submitRequest(Unknown Source)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:437)
		at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:170)
		at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:162)
		at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:100)
		at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:366)
		at jdk.proxy2/jdk.proxy2.$Proxy118.submitRequest(Unknown Source)
		at org.apache.hadoop.ozone.om.protocolPB.Hadoop3OmTransport.submitRequest(Hadoop3OmTransport.java:73)
		at org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB.submitRequest(OzoneManagerProtocolClientSideTranslatorPB.java:340)
		at org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB.createVolume(OzoneManagerProtocolClientSideTranslatorPB.java:362)
		at org.apache.hadoop.ozone.TestSecureOzoneCluster.testAccessControlExceptionOnClient(TestSecureOzoneCluster.java:591)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		... 2 more
	Caused by: java.io.InterruptedIOException: Interrupted while waiting for IO on channel java.nio.channels.SocketChannel[connection-pending remote=10.1.0.101/10.1.0.101:15055]. Total timeout mills is 20000, 17267 millis timeout left.
		at org.apache.hadoop.net.SocketIOWithTimeout$SelectorPool.select(SocketIOWithTimeout.java:350)
		at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:202)
		at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:614)
		at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:668)
		at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:789)
		at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:364)
		at org.apache.hadoop.ipc.Client.getConnection(Client.java:1649)
		at org.apache.hadoop.ipc.Client.call(Client.java:1473)
		... 19 more

org.apache.hadoop.ozone.TestSecureOzoneCluster.testCertificateRotationRecoverableFailure -- Time elapsed: 21.28 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  "2025-05-13 07:49:57,988 [main] INFO  security.OMCertificateClient (DefaultCertificateClient.java:updateCertSerialId(1289)) - Certificate serial ID set to 1395303
2025-05-13 07:49:57,989 [main] INFO  security.OMCertificateClient (DefaultCertificateClient.java:readCertificateFile(247)) - Added certificate 1395303 from file: /tmp/junit-3070183987745344977/om-meta/om/certs/certificate.crt.
2025-05-13 07:49:57,989 [main] INFO  security.OMCertificateClient (DefaultCertificateClient.java:startCertificateRenewerService(1380)) - CertificateRenewerService for om is started with first delay 9010 ms and interval 3333 ms.
2025-05-13 07:49:57,990 [main] INFO  security.OMCertificateClient (DefaultCertificateClient.java:init(717)) - Certificate client init case: 7
2025-05-13 07:49:57,990 [main] INFO  security.OMCertificateClient (DefaultCertificateClient.java:handleCase(778)) - Found certificate file along with KeyPair.
2025-05-13 07:49:57,994 [main] INFO  security.OMCertificateClient (DefaultCertificateClient.java:validateKeyPairAndCertificate(830)) - Keypair validated.
2025-05-13 07:49:57,998 [main] INFO  security.OMCertificateClient (DefaultCertificateClient.java:validateKeyPairAndCertificate(833)) - Keypair validated with certificate.
"
to contain:
  "Error while signing and storing SCM signed certificate." 
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testCertificateRotationRecoverableFailure(TestSecureOzoneCluster.java:1063)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

org.apache.hadoop.ozone.TestSecureOzoneCluster.testSecureOMInitializationFailure -- Time elapsed: 8.759 s <<< ERROR!
java.net.BindException: Problem binding to [pkrvmberfyhpb9w.internal.cloudapp.net:15076] java.net.BindException: Cannot assign requested address; For more details see:  http://wiki.apache.org/hadoop/BindException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:961)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:857)
	at org.apache.hadoop.ipc.Server.bind(Server.java:715)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:1435)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:3364)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:1195)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server.<init>(ProtobufRpcEngine2.java:485)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:452)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:375)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:986)
	at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1414)
	at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1376)
	at org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:695)
	at org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:877)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.setupOm(TestSecureOzoneCluster.java:716)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testSecureOMInitializationFailure(TestSecureOzoneCluster.java:527)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.apache.hadoop.ipc.Server.bind(Server.java:698)
	... 16 more

org.apache.hadoop.ozone.TestSecureOzoneCluster.testDelegationTokenRenewal -- Time elapsed: 8.612 s <<< ERROR!
java.net.BindException: Problem binding to [pkrvmberfyhpb9w.internal.cloudapp.net:15083] java.net.BindException: Cannot assign requested address; For more details see:  http://wiki.apache.org/hadoop/BindException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:961)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:857)
	at org.apache.hadoop.ipc.Server.bind(Server.java:715)
	at org.apache.hadoop.ipc.Server$Listener.<init>(Server.java:1435)
	at org.apache.hadoop.ipc.Server.<init>(Server.java:3364)
	at org.apache.hadoop.ipc.RPC$Server.<init>(RPC.java:1195)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server.<init>(ProtobufRpcEngine2.java:485)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.<init>(ProtobufRpcEngine.java:452)
	at org.apache.hadoop.ipc.ProtobufRpcEngine.getServer(ProtobufRpcEngine.java:375)
	at org.apache.hadoop.ipc.RPC$Builder.build(RPC.java:986)
	at org.apache.hadoop.ozone.om.OzoneManager.startRpcServer(OzoneManager.java:1414)
	at org.apache.hadoop.ozone.om.OzoneManager.getRpcServer(OzoneManager.java:1376)
	at org.apache.hadoop.ozone.om.OzoneManager.<init>(OzoneManager.java:695)
	at org.apache.hadoop.ozone.om.OzoneManager.createOm(OzoneManager.java:877)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.setupOm(TestSecureOzoneCluster.java:716)
	at org.apache.hadoop.ozone.TestSecureOzoneCluster.testDelegationTokenRenewal(TestSecureOzoneCluster.java:640)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at org.apache.hadoop.ipc.Server.bind(Server.java:698)
	... 16 more

