2025-10-20 07:52:32,006 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2025-10-20 07:52:33,678 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2025-10-20 07:52:36,743 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2025-10-20 07:52:38,605 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2025-10-20 07:52:39,056 | ERROR | OMAudit | user=hadoop | ip=10.9.0.17 | op=READ_VOLUME {"volume":"45418-volume-for-prepare"} | ret=FAILURE | 
org.apache.hadoop.ozone.om.exceptions.OMException: Volume 45418-volume-for-prepare is not found
	at org.apache.hadoop.ozone.om.VolumeManagerImpl.getVolumeInfo(VolumeManagerImpl.java:60)
	at org.apache.hadoop.ozone.om.OzoneManager.getVolumeInfo(OzoneManager.java:2804)
 
2025-10-20 07:52:40,361 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2025-10-20 07:52:40,779 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=LIST_VOLUMES {"prevKey":"","prefix":"","maxKeys":"1000","username":"hadoop"} | ret=SUCCESS |  
2025-10-20 07:52:40,967 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=LIST_VOLUMES {"prevKey":"64628-volume-for-cancel","prefix":"","maxKeys":"1000","username":"hadoop"} | ret=SUCCESS |  
